### ISSUE TITLE
[Feature Request] Worldname Included

### ISSUE THREAD

**Issue by RillSoji** [RoverIsADog/InfoHUD#11]
I'd love to see a configurable option to display the world name you're currently in when playing on servers using plugins like Multiverse to provide multiple worlds/dimensions. Thanks for considering and thanks for a great plugin!

**Comment by RoverIsADog** [comment]
Hey, sorry for the late reply. Unfortunately, the goal of this plugin is to emulate the Coordinates Hud datapack and add maybe a few little extras. I feel adding an option specific to users of a specific plugin / server provider will clutter the configuration menu for regular users. 

As such, this will not be implemented for now. But, I will keep this in mind if I decide to overhaul the plugin in the future (e.g. completely custom strings or other plugin integrations).
