### ISSUE TITLE
broken in 1.17.1 & project status?

### ISSUE THREAD

**Issue by raoel** [RoverIsADog/InfoHUD#3]
Hello, I really like this HUD!

Are you still working on it? It's broken on the latest version (1.17.1).
There is a fork that's working: 
https://www.curseforge.com/minecraft/bukkit-plugins/defined-hud    ->   https://github.com/wond-cr/defined-hud

thanks :-D

**Comment by RoverIsADog** [comment]
Thank you for bringing this to my attention. I haven't really kept up with Minecraft in recent times and just assumed that the plugin would continue working. It seems Mojang has once again decided to refactor the NMS structure, breaking everything.

I have fixed the broken paths for NMS 1.17 and made the plugin use the Spigot API by default so hopefully this doesn't happen again in the future. The changes are currently in branch Future.

I will update the listing on Curseforge shortly once I make sure no new bugs were introduced and everything works.

**Comment by raoel** [comment]
thank you! :-)
