### ISSUE TITLE
Disabled player does not exist in playerMap

### ISSUE THREAD

**Issue by owu-1** [RoverIsADog/InfoHUD#8]
If a player has not enabled or disabled InfoHUD, then they are not referenced in the file players.yml and the map ConfigManager.playerMap. Attempting to access these players in ConfigManager.playerMap through the PlayerBedEnterEvent and EntityMountEvent handlers gives an error. Attached are the stack traces.
[partial-log.txt](https://github.com/RoverIsADog/InfoHUD/files/10915369/partial-log.txt)

**Comment by RoverIsADog** [comment]
Nice catch! I'll try to get it fixed by tomorrow.

**Comment by RoverIsADog** [comment]
Fixed in 9b7f297 (Version 1.5.2)
