### ISSUE TITLE
Feature Request: top of screen position option

### ISSUE THREAD

**Issue by joshrosario310** [RoverIsADog/InfoHUD#9]

**Comment by joshrosario310** [comment]
Or possibly bottom right

**Comment by RoverIsADog** [comment]
This plugin is intended to be usable by vanilla clients connecting to your server. As such it uses the vanilla "actionbar" feature, which is also used by the sleep and mount messages. The location of the actionbar message can't be changed. 

If you want to display that info anywhere for yourself, you'll want to look at mods such as [MiniHUD](https://www.curseforge.com/minecraft/mc-mods/minihud).
